#!/usr/bin/env bash
# disable_cpu_embed.sh — stop the CPU-embed fallback pool.
#
# rag-embed-cpu exists as a 5xx fallback when the GPU embedder is overloaded,
# but on a 6 GB / 32 GB-host machine it competes for RAM and OOM-loops, which
# fills swap and slows the whole stack. Disable it when GPU embed is healthy.
#
# Usage:
#   scripts/disable_cpu_embed.sh           # stop + scale to 0 (this session)
#   scripts/disable_cpu_embed.sh --persist # also patch override file so it
#                                          # stays disabled across `make start`
#   scripts/disable_cpu_embed.sh --restore # bring it back

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SERVICE="rag-embed-cpu"
OVERRIDE_FILE="docker-compose.override.yml"
DISABLE_OVERRIDE="docker-compose.cpu-embed-off.yml"

mode="${1:-}"

stop_running() {
    local cids
    cids=$(docker ps -aq --filter "name=${SERVICE}" || true)
    if [[ -z "$cids" ]]; then
        echo "no ${SERVICE} containers running"
        return
    fi
    echo "stopping ${SERVICE} containers..."
    docker compose stop "$SERVICE" 2>/dev/null || true
    docker compose rm -fsv "$SERVICE" 2>/dev/null || true
    # Belt-and-braces: any orphan replicas
    for c in $cids; do docker rm -fv "$c" >/dev/null 2>&1 || true; done
    echo "done."
}

write_persist_overlay() {
    cat > "$DISABLE_OVERRIDE" <<'YAML'
# Auto-generated by scripts/disable_cpu_embed.sh --persist
# Replaces rag-embed-cpu with a no-op sleeper so nginx's depends_on
# (condition: service_started) is satisfied without loading the ~2 GB CPU
# embedding model. Fallback requests will 502 — clients already handle this
# the same as a transient backend failure.
# Restore: ./scripts/disable_cpu_embed.sh --restore
services:
  rag-embed-cpu:
    image: alpine:3.20
    entrypoint: ["sh", "-c", "sleep infinity"]
    command: []
    healthcheck:
      disable: true
    deploy: {}
    volumes: []
    environment: []
    restart: "no"
YAML
    echo "wrote $DISABLE_OVERRIDE"
    echo "to apply: docker compose -f docker-compose.yml -f $OVERRIDE_FILE -f $DISABLE_OVERRIDE up -d"
}

case "$mode" in
    --persist)
        stop_running
        write_persist_overlay
        ;;
    --restore)
        rm -f "$DISABLE_OVERRIDE" && echo "removed $DISABLE_OVERRIDE"
        echo "next \`make start\` will bring rag-embed-cpu back."
        ;;
    "" )
        stop_running
        echo
        echo "tip: pass --persist to keep it off across restarts."
        ;;
    *)
        echo "usage: $0 [--persist|--restore]" >&2
        exit 2
        ;;
esac

echo
echo "current memory:"
free -h | awk 'NR==1 || NR==2 || NR==3'
echo
echo "remaining containers:"
docker ps --format "  {{.Names}}\t{{.Status}}" | sed 's/^/  /'
